# Centroid + Feature Mean Tracking

Barebones tracking with windowed cost matrices and Hungarian assignment. Methods: centroid-only, feature-mean-only, centroid plus a small clipped feature-mean correction, and a centroid-feature prototype tracker that keeps a running feature average per active track. No shape terms and no raw-intensity dependency. The search window is not applied to the 3-frame method.

In [5]:
from pathlib import Path
import importlib.util
import json
import sys

import pandas as pd
import torch

repo_root = Path.cwd()
while repo_root != repo_root.parent and not (repo_root / "scripts" / "evaluation" / "feature_mean_tracking.py").exists():
    repo_root = repo_root.parent

module_path = repo_root / "scripts" / "evaluation" / "feature_mean_tracking.py"
if str(module_path.parent) not in sys.path:
    sys.path.insert(0, str(module_path.parent))
spec = importlib.util.spec_from_file_location("feature_mean_tracking", module_path)
feature_mean_tracking = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = feature_mean_tracking
spec.loader.exec_module(feature_mean_tracking)

FeatureMeanConfig = feature_mean_tracking.FeatureMeanConfig
run_feature_mean_tracking = feature_mean_tracking.run_feature_mean_tracking
save_result = feature_mean_tracking.save_result

print(f"repo_root: {repo_root}")
print(f"cuda: {torch.cuda.is_available()} devices={torch.cuda.device_count()}")

repo_root: /nfs/scratch2/inacio/code/llsm/spatialdino/spatialdino
cuda: True devices=1

In [6]:
# Edit these paths before running.
INPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/")
SEGMENTATION_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/seg/")
OUTPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/")

MAX_FRAMES = None
COMPUTE_GT_METRICS = False

METHODS = ("centroid", "feature_mean", "centroid_feature", "centroid_feature_prototype")
TRACKS_METHOD = "centroid_feature_prototype"
CENTROID_FEATURE_WEIGHT = 0.1
FEATURE_NORM_CLIP = 10.0
Z_WEIGHT = 2.5
MAX_DISTANCE_XY = 20.0
MAX_DISTANCE_Z = 10.0

DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

In [7]:
# # Edit these paths before running.
# INPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/virus_gap/n_600/gap_7/rope/")
# SEGMENTATION_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/virus_gap/n_600/gap_7/gt/")
# OUTPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/virus_gap/n_600/gap_7/feature_mean_tracking/")

# MAX_FRAMES = None
# COMPUTE_GT_METRICS = True

# METHODS = ("centroid", "feature_mean", "centroid_feature", "centroid_feature_prototype")
# TRACKS_METHOD = "centroid_feature_prototype"
# CENTROID_FEATURE_WEIGHT = 0.1
# FEATURE_NORM_CLIP = 10.0
# Z_WEIGHT = 2.5
# MAX_DISTANCE_XY = 20.0
# MAX_DISTANCE_Z = 10.0

# DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

In [8]:
config = FeatureMeanConfig(
    n_features=384,
    samples_per_object=256,
    seed=12345,
    device=DEVICE,
    methods=METHODS,
    tracks_method=TRACKS_METHOD,
    centroid_feature_weight=CENTROID_FEATURE_WEIGHT,
    feature_norm_clip=FEATURE_NORM_CLIP,
    z_weight=Z_WEIGHT,
    max_distance_xy=MAX_DISTANCE_XY,
    max_distance_z=MAX_DISTANCE_Z,
    max_frames=MAX_FRAMES,
    compute_gt_metrics=COMPUTE_GT_METRICS,
    progress=True,
)

config

FeatureMeanConfig(n_features=384, samples_per_object=256, seed=12345, device='cuda:0', methods=('centroid', 'feature_mean', 'centroid_feature', 'centroid_feature_prototype'), tracks_method='centroid_feature_prototype', centroid_feature_weight=0.1, feature_norm_clip=10.0, z_weight=2.5, max_distance_xy=20.0, max_distance_z=10.0, three_frame_direct_weight=0.25, three_frame_candidate_top_k=8, three_frame_time_limit_seconds=60.0, max_frames=None, compute_gt_metrics=False, progress=True, object_batch_size=512, feature_channel_block=64, sample_batch_size=131072)

In [9]:
result = run_feature_mean_tracking(
    INPUT_PATH,
    SEGMENTATION_PATH,
    config=config,
)

saved_paths = save_result(result, OUTPUT_PATH)
print(json.dumps(saved_paths, indent=2))

[feature-mean-tracking] found 51 frame(s); using 384/390 feature channel(s), 256 sample(s)/object, methods=('centroid', 'feature_mean', 'centroid_feature', 'centroid_feature_prototype'), device=cuda:0

feature means:   0%|                                                                                          …

[feature-mean-tracking] feature means completed in 81.96s

adjacent pairs:   0%|                                                                                         …

prototype pairs:   0%|                                                                                        …

[feature-mean-tracking] matching and tracks completed in 1.13s; total 83.13s
{
  "tracks_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks.csv",
  "assignments_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/assignments.csv",
  "timings_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/timings.csv",
  "config_json": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/config.json",
  "tracks_centroid_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_centroid.csv",
  "tracks_centroid_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_by_method/centroid/tracks.csv",
  "tracks_feature_mean_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_feature_mean.csv",
  "tracks_feature_mean_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_by_method/feature_mean/tracks.csv",
  "tracks_centroid_feature_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_centroid_feature.csv",
  "tracks_centroid_feature_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_by_method/centroid_feature/tracks.csv",
  "tracks_centroid_feature_prototype_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_centroid_feature_prototype.csv",
  "tracks_centroid_feature_prototype_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/bryan/dino/care/642_virus/rope/tracking/tracks_by_method/centroid_feature_prototype/tracks.csv",
  "tracks_default_method": "centroid_feature_prototype"
}

In [113]:
display(result.metrics if result.metrics is not None else pd.DataFrame())
display(result.pair_metrics.head(20) if result.pair_metrics is not None else pd.DataFrame())

,method,frame_pairs,trackable_count,link_pred_count,link_tp,link_fp,link_fn,precision,recall,f1,median_centroid_scale,median_feature_scale,centroid_feature_weight,feature_norm_clip
0,centroid,6,3600,3600,3183,417,417,0.884167,0.884167,0.884167,263.08223,NaN,NaN,NaN
1,feature_mean,6,3600,3600,1844,1756,1756,0.512222,0.512222,0.512222,NaN,0.060884,NaN,NaN
2,centroid_feature,6,3600,3600,3186,414,414,0.885000,0.885000,0.885000,263.08223,0.060884,0.1,10.0
3,centroid_feature_prototype,6,3600,3600,3186,414,414,0.885000,0.885000,0.885000,263.08223,0.055860,0.1,10.0

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_count,cand_count,trackable_count,link_pred_count,link_tp,link_fp,link_fn,precision,recall,f1,centroid_scale,feature_scale,centroid_feature_weight,feature_norm_clip
0,centroid,0,1,00,08,600,600,600,600,495,105,105,0.825000,0.825000,0.825000,262.154449,NaN,NaN,NaN
1,feature_mean,0,1,00,08,600,600,600,600,291,309,309,0.485000,0.485000,0.485000,NaN,0.058122,NaN,NaN
2,centroid_feature,0,1,00,08,600,600,600,600,495,105,105,0.825000,0.825000,0.825000,262.154449,0.058122,0.1,10.0
3,centroid,1,2,08,16,600,600,600,600,541,59,59,0.901667,0.901667,0.901667,262.318420,NaN,NaN,NaN
4,feature_mean,1,2,08,16,600,600,600,600,286,314,314,0.476667,0.476667,0.476667,NaN,0.060270,NaN,NaN
5,centroid_feature,1,2,08,16,600,600,600,600,540,60,60,0.900000,0.900000,0.900000,262.318420,0.060270,0.1,10.0
6,centroid,2,3,16,24,600,600,600,600,530,70,70,0.883333,0.883333,0.883333,262.769379,NaN,NaN,NaN
7,feature_mean,2,3,16,24,600,600,600,600,307,293,293,0.511667,0.511667,0.511667,NaN,0.062683,NaN,NaN
8,centroid_feature,2,3,16,24,600,600,600,600,532,68,68,0.886667,0.886667,0.886667,262.769379,0.062683,0.1,10.0
9,centroid,3,4,24,32,600,600,600,600,539,61,61,0.898333,0.898333,0.898333,263.395081,NaN,NaN,NaN
10,feature_mean,3,4,24,32,600,600,600,600,305,295,295,0.508333,0.508333,0.508333,NaN,0.061144,NaN,NaN
11,centroid_feature,3,4,24,32,600,600,600,600,540,60,60,0.900000,0.900000,0.900000,263.395081,0.061144,0.1,10.0
12,centroid,4,5,32,40,600,600,600,600,548,52,52,0.913333,0.913333,0.913333,263.994995,NaN,NaN,NaN
13,feature_mean,4,5,32,40,600,600,600,600,330,270,270,0.550000,0.550000,0.550000,NaN,0.060624,NaN,NaN
14,centroid_feature,4,5,32,40,600,600,600,600,543,57,57,0.905000,0.905000,0.905000,263.994995,0.060624,0.1,10.0
15,centroid,5,6,40,48,600,600,600,600,530,70,70,0.883333,0.883333,0.883333,264.419952,NaN,NaN,NaN
16,feature_mean,5,6,40,48,600,600,600,600,325,275,275,0.541667,0.541667,0.541667,NaN,0.062225,NaN,NaN
17,centroid_feature,5,6,40,48,600,600,600,600,536,64,64,0.893333,0.893333,0.893333,264.419952,0.062225,0.1,10.0
18,centroid_feature_prototype,0,1,00,08,600,600,600,600,495,105,105,0.825000,0.825000,0.825000,262.154449,0.058122,0.1,10.0
19,centroid_feature_prototype,1,2,08,16,600,600,600,600,546,54,54,0.910000,0.910000,0.910000,262.318420,0.057129,0.1,10.0

In [98]:
display(result.assignments.head(50))

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_label,assigned_cand_label,cost,is_true_link,prototype_observations
0,centroid,0,1,00,04,1,1,0.030485,True,NaN
1,centroid,0,1,00,04,2,2,0.035113,True,NaN
2,centroid,0,1,00,04,3,3,0.111295,True,NaN
3,centroid,0,1,00,04,4,4,0.070280,True,NaN
4,centroid,0,1,00,04,5,252,0.130346,False,NaN
5,centroid,0,1,00,04,6,6,0.063838,True,NaN
6,centroid,0,1,00,04,7,7,0.028826,True,NaN
7,centroid,0,1,00,04,8,8,0.113979,True,NaN
8,centroid,0,1,00,04,9,9,0.022566,True,NaN
9,centroid,0,1,00,04,10,102,0.027215,False,NaN
10,centroid,0,1,00,04,11,11,0.034515,True,NaN
11,centroid,0,1,00,04,12,12,0.029849,True,NaN
12,centroid,0,1,00,04,13,87,0.078915,False,NaN
13,centroid,0,1,00,04,14,14,0.031601,True,NaN
14,centroid,0,1,00,04,15,15,0.118668,True,NaN
15,centroid,0,1,00,04,16,16,0.040157,True,NaN
16,centroid,0,1,00,04,17,210,0.030349,False,NaN
17,centroid,0,1,00,04,18,18,0.112733,True,NaN
18,centroid,0,1,00,04,19,19,0.062494,True,NaN
19,centroid,0,1,00,04,20,20,0.038327,True,NaN
20,centroid,0,1,00,04,21,21,0.047015,True,NaN
21,centroid,0,1,00,04,22,22,0.059724,True,NaN
22,centroid,0,1,00,04,23,23,0.040660,True,NaN
23,centroid,0,1,00,04,24,24,0.047812,True,NaN
24,centroid,0,1,00,04,25,25,0.035465,True,NaN
25,centroid,0,1,00,04,26,26,0.012101,True,NaN
26,centroid,0,1,00,04,27,27,0.038287,True,NaN
27,centroid,0,1,00,04,28,28,0.046673,True,NaN
28,centroid,0,1,00,04,29,29,0.079393,True,NaN
29,centroid,0,1,00,04,30,30,0.029423,True,NaN
30,centroid,0,1,00,04,31,31,0.041111,True,NaN
31,centroid,0,1,00,04,32,32,0.032759,True,NaN
32,centroid,0,1,00,04,33,33,0.243537,True,NaN
33,centroid,0,1,00,04,34,34,0.013663,True,NaN
34,centroid,0,1,00,04,35,35,0.041479,True,NaN
35,centroid,0,1,00,04,36,36,0.069771,True,NaN
36,centroid,0,1,00,04,37,269,0.083535,False,NaN
37,centroid,0,1,00,04,38,38,0.056124,True,NaN
38,centroid,0,1,00,04,39,39,0.023260,True,NaN
39,centroid,0,1,00,04,40,40,0.054626,True,NaN
40,centroid,0,1,00,04,41,41,0.023364,True,NaN
41,centroid,0,1,00,04,42,42,0.047764,True,NaN
42,centroid,0,1,00,04,43,43,0.048170,True,NaN
43,centroid,0,1,00,04,44,44,0.072785,True,NaN
44,centroid,0,1,00,04,45,45,0.045620,True,NaN
45,centroid,0,1,00,04,46,46,0.026356,True,NaN
46,centroid,0,1,00,04,47,47,0.052246,True,NaN
47,centroid,0,1,00,04,48,156,0.178931,False,NaN
48,centroid,0,1,00,04,49,49,0.052077,True,NaN
49,centroid,0,1,00,04,50,50,0.011638,True,NaN

In [99]:
display(result.tracks.head(50))

    track_id  start   t           x           y          z    A  track_length
0          1      1   1  309.000000  223.000000  12.000000  1.0            13
1          1      1   2  316.666656  224.079361  12.460318  1.0            13
2          1      1   3  309.758057  214.370972   9.225806  1.0            13
3          1      1   4  286.432831  225.343277  16.179104  1.0            13
4          1      1   5  289.343750  247.937500  28.500000  1.0            13
5          1      1   6  287.671875  252.109375  36.562500  1.0            13
6          1      1   7  261.671875  236.453125  47.359375  1.0            13
7          1      1   8  246.079361  244.174606  51.269840  1.0            13
8          1      1   9  228.344315  289.781433  63.452095  1.0            13
9          1      1  10  228.590912  311.818176  60.878788  1.0            13
10         1      1  11  223.393936  318.333344  57.242424  1.0            13
11         1      1  12  213.731339  317.567169  57.537312  1.0            13
12         1      1  13  212.298508  309.671631  53.298508  1.0            13
13         2      1   1  338.000000  422.000000  40.000000  1.0            13
14         2      1   2  344.640625  421.781250  42.437500  1.0            13
15         2      1   3  341.393951  418.666656  38.242424  1.0            13
16         2      1   4  335.646149  418.569244  39.353848  1.0            13
17         2      1   5  340.338470  406.907684  38.523075  1.0            13
18         2      1   6  347.218750  401.453125  32.000000  1.0            13
19         2      1   7  338.507690  398.215393  34.246155  1.0            13
20         2      1   8  335.420288  401.072449  41.028984  1.0            13
21         2      1   9  346.878784  389.727264  39.393940  1.0            13
22         2      1  10  343.727264  392.348480  40.590908  1.0            13
23         2      1  11  346.181824  392.409088  39.878788  1.0            13
24         2      1  12  344.927551  403.420288  38.971016  1.0            13
25         2      1  13  343.292297  408.553833  36.538460  1.0            13
26         3      1   1   38.000000  259.000000  49.000000  1.0            13
27         3      1   2   30.507692  237.815384  56.061539  1.0            13
28         3      1   3   53.671875  246.890625  54.437500  1.0            13
29         3      1   4   60.311474  244.737701  51.868851  1.0            13
30         3      1   5   72.969231  238.707687  60.215385  1.0            13
31         3      1   6   48.281250  221.593750  59.859375  1.0            13
32         3      1   7   42.599998  196.399994  56.599998  1.0            13
33         3      1   8   44.923077  181.399994  63.784615  1.0            13
34         3      1   9   78.500000  171.875000  66.000000  1.0            13
35         3      1  10   98.047623  165.365082  64.412697  1.0            13
36         3      1  11  105.687500  158.250000  65.609375  1.0            13
37         3      1  12  104.646156  158.600006  59.415386  1.0            13
38         3      1  13  118.000000  162.478256  52.463768  1.0            13
39         4      1   1   18.000000  415.000000  29.000000  1.0            13
40         4      1   2   22.400000  415.057129  22.000000  1.0            13
41         4      1   3   16.500000  409.500000  20.500000  1.0            13
42         4      1   4   15.132353  446.470581  13.720589  1.0            13
43         4      1   5   23.353846  457.569244   6.646154  1.0            13
44         4      1   6   22.586666  455.506653   3.960000  1.0            13
45         4      1   7   27.500000  450.500000   1.083333  1.0            13
46         4      1   8   20.413794  442.655182   1.637931  1.0            13
47         4      1   9   18.372549  457.725494   1.294118  1.0            13
48         4      1  10   15.656250  476.875000   3.281250  1.0            13
49         4      1  11   13.810811  495.864868   1.135135  1.0            13