# Feature/Shape GT Tracking Experiment

Fresh sandbox for dense adjacent-frame matching from GT segmentation masks and SpatialDINO features. The GT label IDs are used only for scoring after costs and Hungarian assignments are computed.

In [32]:
from pathlib import Path
import importlib.util
import sys

repo_root = Path.cwd().resolve()
while not (repo_root / "pyproject.toml").is_file() and repo_root != repo_root.parent:
    repo_root = repo_root.parent
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

import torch

module_path = repo_root / "scripts" / "evaluation" / "feature_shape_tracking_experiment.py"
if str(module_path.parent) not in sys.path:
    sys.path.insert(0, str(module_path.parent))
spec = importlib.util.spec_from_file_location("feature_shape_tracking_experiment", module_path)
experiment = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = experiment
spec.loader.exec_module(experiment)

ExperimentConfig = experiment.ExperimentConfig
aggregate_summary = experiment.aggregate_summary
run_adjacent_tracking_experiment = experiment.run_adjacent_tracking_experiment
save_result = experiment.save_result

print(f"repo_root: {repo_root}")
print(f"cuda: {torch.cuda.is_available()} devices={torch.cuda.device_count()}")

repo_root: /nfs/scratch2/inacio/code/llsm/spatialdino/spatialdino
cuda: True devices=1

In [43]:
# Edit these paths before running.
INPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/rope/")
GT_SEGMENTATION_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/gt/")
OUTPUT_PATH = "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/"

# For a fast first pass, set MAX_FRAMES=20 or MAX_ADJACENT_PAIRS=3.
MAX_FRAMES = None
MAX_ADJACENT_PAIRS = None

# Large centroid gate applied before Hungarian assignment. Set enabled=False for fully dense matching.
SEARCH_RADIUS_ENABLED = True
SEARCH_RADIUS_XY = 50.0
SEARCH_RADIUS_Z = 25.0

In [44]:
visible_cuda_devices = tuple(f"cuda:{idx}" for idx in range(torch.cuda.device_count()))
devices = visible_cuda_devices if visible_cuda_devices else ("cpu",)

config = ExperimentConfig(
    n_features=384,
    samples_per_object=128,
    n_feature_projections=64,
    n_shape_pairs=512,
    n_shape_quantiles=64,
    shape_weight=0.1,
    methods=("feature_mean", "sliced_wasserstein", "sliced_wasserstein_shape"),
    seed=12345,
    feature_channel_block=64,
    object_batch_size=256,
    sample_batch_size=131_072,
    cost_block_rows=1024,
    mask_workers=8,
    signature_workers=len(devices),
    devices=devices,
    pair_device=devices[0],
    use_float16_cost=False,
    torch_threads_per_worker=1,
    max_frames=MAX_FRAMES,
    max_adjacent_pairs=MAX_ADJACENT_PAIRS,
    search_radius_enabled=SEARCH_RADIUS_ENABLED,
    search_radius_xy=SEARCH_RADIUS_XY,
    search_radius_z=SEARCH_RADIUS_Z,
    progress=True,
)

config

ExperimentConfig(n_features=384, samples_per_object=128, n_feature_projections=64, n_shape_pairs=512, n_shape_quantiles=64, shape_weight=0.1, methods=('feature_mean', 'sliced_wasserstein', 'sliced_wasserstein_shape'), seed=12345, feature_channel_block=64, object_batch_size=256, sample_batch_size=131072, cost_block_rows=1024, mask_workers=8, signature_workers=1, devices=('cuda:0',), pair_device='cuda:0', use_float16_cost=False, torch_threads_per_worker=1, max_frames=None, max_adjacent_pairs=None, search_radius_enabled=True, search_radius_xy=50.0, search_radius_z=25.0, progress=True)

In [45]:
result = run_adjacent_tracking_experiment(
    INPUT_PATH,
    GT_SEGMENTATION_PATH,
    config=config,
)

aggregate = aggregate_summary(result.summary)
display(aggregate)

[feature-shape-tracking] found 13 frame(s); using 384/390 feature channel(s), 128 sample(s)/object, 64 projection(s)
[feature-shape-tracking] signature devices=['cuda:0']; pair_device=cuda:0
[feature-shape-tracking] centroid search radius enabled: xy=50, z=25
[feature-shape-tracking] preparing mask metadata for 13 frame(s) with 8 worker(s)

mask metadata:   0%|                                                                                          …

[feature-shape-tracking] mask metadata completed in 1.10s
[feature-shape-tracking] building feature signatures for 13 frame(s) on cuda:0

feature signatures:   0%|                                                                                     …

[feature-shape-tracking] feature signatures completed in 49.77s
[feature-shape-tracking] evaluating 12 adjacent frame pair(s) on cuda:0

adjacent pairs:   0%|                                                                                         …

[feature-shape-tracking] pair 1/12: 00->04 dense matrix 300x300

00->04 mean:   0%|                                                                                            …

00->04 SW:   0%|                                                                                              …

00->04 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 2/12: 04->08 dense matrix 300x300

04->08 mean:   0%|                                                                                            …

04->08 SW:   0%|                                                                                              …

04->08 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 3/12: 08->12 dense matrix 300x300

08->12 mean:   0%|                                                                                            …

08->12 SW:   0%|                                                                                              …

08->12 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 4/12: 12->16 dense matrix 300x300

12->16 mean:   0%|                                                                                            …

12->16 SW:   0%|                                                                                              …

12->16 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 5/12: 16->20 dense matrix 300x300

16->20 mean:   0%|                                                                                            …

16->20 SW:   0%|                                                                                              …

16->20 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 6/12: 20->24 dense matrix 300x300

20->24 mean:   0%|                                                                                            …

20->24 SW:   0%|                                                                                              …

20->24 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 7/12: 24->28 dense matrix 300x300

24->28 mean:   0%|                                                                                            …

24->28 SW:   0%|                                                                                              …

24->28 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 8/12: 28->32 dense matrix 300x300

28->32 mean:   0%|                                                                                            …

28->32 SW:   0%|                                                                                              …

28->32 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 9/12: 32->36 dense matrix 300x300

32->36 mean:   0%|                                                                                            …

32->36 SW:   0%|                                                                                              …

32->36 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 10/12: 36->40 dense matrix 300x300

36->40 mean:   0%|                                                                                            …

36->40 SW:   0%|                                                                                              …

36->40 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 11/12: 40->44 dense matrix 300x300

40->44 mean:   0%|                                                                                            …

40->44 SW:   0%|                                                                                              …

40->44 shape:   0%|                                                                                           …

[feature-shape-tracking] pair 12/12: 44->48 dense matrix 300x300

44->48 mean:   0%|                                                                                            …

44->48 SW:   0%|                                                                                              …

44->48 shape:   0%|                                                                                           …

[feature-shape-tracking] adjacent pair evaluation completed in 0.79s; total 51.68s

,method,frame_pairs,trackable_count,hungarian_accuracy,top1_accuracy,mean_true_rank,median_pair_margin,mean_pair_margin,link_pred_count,link_tp,...,radius_pair_count,radius_allowed_count,radius_allowed_fraction,radius_relaxed_ref_count,radius_relaxed_ref_fraction,true_link_outside_radius_count,true_link_outside_radius_fraction,assigned_outside_radius_count,assigned_outside_radius_fraction,assigned_relaxed_ref_count
0,feature_mean,12,3600,0.729444,0.686111,1.836111,0.004958,-34444.447826,3600,2626,...,1080000,26418,0.024461,1,0.000278,157,0.043611,9,0.0025,1
1,sliced_wasserstein,12,3600,0.737778,0.683333,1.833056,0.000025,-34444.444407,3600,2656,...,1080000,26418,0.024461,1,0.000278,157,0.043611,9,0.0025,1
2,sliced_wasserstein_shape,12,3600,0.709167,0.643056,1.921667,0.066113,-156766.774713,3600,2553,...,1080000,26418,0.024461,1,0.000278,157,0.043611,9,0.0025,1

In [46]:
display(
    result.summary.sort_values(
        ["method", "ref_frame_index"],
        kind="mergesort",
    )
)

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_count,cand_count,trackable_count,hungarian_correct,hungarian_accuracy,...,assigned_outside_radius_count,assigned_outside_radius_fraction,assigned_relaxed_ref_count,link_pred_count,link_tp,link_fp,link_fn,link_precision,link_recall,link_f1
0,feature_mean,0,1,00,04,300,300,300,201,0.670000,...,0,0.000000,0,300,201,99,99,0.670000,0.670000,0.670000
3,feature_mean,1,2,04,08,300,300,300,211,0.703333,...,1,0.003333,0,300,211,89,89,0.703333,0.703333,0.703333
6,feature_mean,2,3,08,12,300,300,300,202,0.673333,...,1,0.003333,0,300,202,98,98,0.673333,0.673333,0.673333
9,feature_mean,3,4,12,16,300,300,300,213,0.710000,...,1,0.003333,0,300,213,87,87,0.710000,0.710000,0.710000
12,feature_mean,4,5,16,20,300,300,300,235,0.783333,...,0,0.000000,0,300,235,65,65,0.783333,0.783333,0.783333
15,feature_mean,5,6,20,24,300,300,300,224,0.746667,...,1,0.003333,0,300,224,76,76,0.746667,0.746667,0.746667
18,feature_mean,6,7,24,28,300,300,300,189,0.630000,...,0,0.000000,0,300,189,111,111,0.630000,0.630000,0.630000
21,feature_mean,7,8,28,32,300,300,300,214,0.713333,...,0,0.000000,0,300,214,86,86,0.713333,0.713333,0.713333
24,feature_mean,8,9,32,36,300,300,300,214,0.713333,...,1,0.003333,0,300,214,86,86,0.713333,0.713333,0.713333
27,feature_mean,9,10,36,40,300,300,300,254,0.846667,...,2,0.006667,0,300,254,46,46,0.846667,0.846667,0.846667
30,feature_mean,10,11,40,44,300,300,300,240,0.800000,...,0,0.000000,0,300,240,60,60,0.800000,0.800000,0.800000
33,feature_mean,11,12,44,48,300,300,300,229,0.763333,...,2,0.006667,1,300,229,71,71,0.763333,0.763333,0.763333
1,sliced_wasserstein,0,1,00,04,300,300,300,208,0.693333,...,0,0.000000,0,300,208,92,92,0.693333,0.693333,0.693333
4,sliced_wasserstein,1,2,04,08,300,300,300,215,0.716667,...,1,0.003333,0,300,215,85,85,0.716667,0.716667,0.716667
7,sliced_wasserstein,2,3,08,12,300,300,300,204,0.680000,...,1,0.003333,0,300,204,96,96,0.680000,0.680000,0.680000
10,sliced_wasserstein,3,4,12,16,300,300,300,227,0.756667,...,1,0.003333,0,300,227,73,73,0.756667,0.756667,0.756667
13,sliced_wasserstein,4,5,16,20,300,300,300,233,0.776667,...,0,0.000000,0,300,233,67,67,0.776667,0.776667,0.776667
16,sliced_wasserstein,5,6,20,24,300,300,300,228,0.760000,...,1,0.003333,0,300,228,72,72,0.760000,0.760000,0.760000
19,sliced_wasserstein,6,7,24,28,300,300,300,195,0.650000,...,0,0.000000,0,300,195,105,105,0.650000,0.650000,0.650000
22,sliced_wasserstein,7,8,28,32,300,300,300,206,0.686667,...,0,0.000000,0,300,206,94,94,0.686667,0.686667,0.686667
25,sliced_wasserstein,8,9,32,36,300,300,300,218,0.726667,...,1,0.003333,0,300,218,82,82,0.726667,0.726667,0.726667
28,sliced_wasserstein,9,10,36,40,300,300,300,252,0.840000,...,2,0.006667,0,300,252,48,48,0.840000,0.840000,0.840000
31,sliced_wasserstein,10,11,40,44,300,300,300,236,0.786667,...,0,0.000000,0,300,236,64,64,0.786667,0.786667,0.786667
34,sliced_wasserstein,11,12,44,48,300,300,300,234,0.780000,...,2,0.006667,1,300,234,66,66,0.780000,0.780000,0.780000
2,sliced_wasserstein_shape,0,1,00,04,300,300,300,209,0.696667,...,0,0.000000,0,300,209,91,91,0.696667,0.696667,0.696667
5,sliced_wasserstein_shape,1,2,04,08,300,300,300,208,0.693333,...,1,0.003333,0,300,208,92,92,0.693333,0.693333,0.693333
8,sliced_wasserstein_shape,2,3,08,12,300,300,300,198,0.660000,...,1,0.003333,0,300,198,102,102,0.660000,0.660000,0.660000
11,sliced_wasserstein_shape,3,4,12,16,300,300,300,207,0.690000,...,1,0.003333,0,300,207,93,93,0.690000,0.690000,0.690000
14,sliced_wasserstein_shape,4,5,16,20,300,300,300,217,0.723333,...,0,0.000000,0,300,217,83,83,0.723333,0.723333,0.723333
17,sliced_wasserstein_shape,5,6,20,24,300,300,300,224,0.746667,...,1,0.003333,0,300,224,76,76,0.746667,0.746667,0.746667
20,sliced_wasserstein_shape,6,7,24,28,300,300,300,187,0.623333,...,0,0.000000,0,300,187,113,113,0.623333,0.623333,0.623333
23,sliced_wasserstein_shape,7,8,28,32,300,300,300,197,0.656667,...,0,0.000000,0,300,197,103,103,0.656667,0.656667,0.656667
26,sliced_wasserstein_shape,8,9,32,36,300,300,300,213,0.710000,...,1,0.003333,0,300,213,87,87,0.710000,0.710000,0.710000
29,sliced_wasserstein_shape,9,10,36,40,300,300,300,241,0.803333,...,2,0.006667,0,300,241,59,59,0.803333,0.803333,0.803333
32,sliced_wasserstein_shape,10,11,40,44,300,300,300,236,0.786667,...,0,0.000000,0,300,236,64,64,0.786667,0.786667,0.786667
35,sliced_wasserstein_shape,11,12,44,48,300,300,300,216,0.720000,...,2,0.006667,1,300,216,84,84,0.720000,0.720000,0.720000

In [47]:
display(
    result.link_metrics.sort_values(
        ["method", "ref_frame_index"],
        kind="mergesort",
    )
)

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_count,cand_count,trackable_count,link_pred_count,link_tp,...,radius_pair_count,radius_allowed_count,radius_allowed_fraction,radius_relaxed_ref_count,radius_relaxed_ref_fraction,true_link_outside_radius_count,true_link_outside_radius_fraction,assigned_outside_radius_count,assigned_outside_radius_fraction,assigned_relaxed_ref_count
0,feature_mean,0,1,00,04,300,300,300,300,201,...,90000,2441,0.027122,0,0.000000,13,0.043333,0,0.000000,0
3,feature_mean,1,2,04,08,300,300,300,300,211,...,90000,2395,0.026611,0,0.000000,16,0.053333,1,0.003333,0
6,feature_mean,2,3,08,12,300,300,300,300,202,...,90000,2325,0.025833,0,0.000000,10,0.033333,1,0.003333,0
9,feature_mean,3,4,12,16,300,300,300,300,213,...,90000,2271,0.025233,0,0.000000,16,0.053333,1,0.003333,0
12,feature_mean,4,5,16,20,300,300,300,300,235,...,90000,2231,0.024789,0,0.000000,8,0.026667,0,0.000000,0
15,feature_mean,5,6,20,24,300,300,300,300,224,...,90000,2187,0.024300,0,0.000000,11,0.036667,1,0.003333,0
18,feature_mean,6,7,24,28,300,300,300,300,189,...,90000,2139,0.023767,0,0.000000,18,0.060000,0,0.000000,0
21,feature_mean,7,8,28,32,300,300,300,300,214,...,90000,2105,0.023389,0,0.000000,16,0.053333,0,0.000000,0
24,feature_mean,8,9,32,36,300,300,300,300,214,...,90000,2072,0.023022,0,0.000000,17,0.056667,1,0.003333,0
27,feature_mean,9,10,36,40,300,300,300,300,254,...,90000,2073,0.023033,0,0.000000,9,0.030000,2,0.006667,0
30,feature_mean,10,11,40,44,300,300,300,300,240,...,90000,2093,0.023256,0,0.000000,11,0.036667,0,0.000000,0
33,feature_mean,11,12,44,48,300,300,300,300,229,...,90000,2086,0.023178,1,0.003333,12,0.040000,2,0.006667,1
1,sliced_wasserstein,0,1,00,04,300,300,300,300,208,...,90000,2441,0.027122,0,0.000000,13,0.043333,0,0.000000,0
4,sliced_wasserstein,1,2,04,08,300,300,300,300,215,...,90000,2395,0.026611,0,0.000000,16,0.053333,1,0.003333,0
7,sliced_wasserstein,2,3,08,12,300,300,300,300,204,...,90000,2325,0.025833,0,0.000000,10,0.033333,1,0.003333,0
10,sliced_wasserstein,3,4,12,16,300,300,300,300,227,...,90000,2271,0.025233,0,0.000000,16,0.053333,1,0.003333,0
13,sliced_wasserstein,4,5,16,20,300,300,300,300,233,...,90000,2231,0.024789,0,0.000000,8,0.026667,0,0.000000,0
16,sliced_wasserstein,5,6,20,24,300,300,300,300,228,...,90000,2187,0.024300,0,0.000000,11,0.036667,1,0.003333,0
19,sliced_wasserstein,6,7,24,28,300,300,300,300,195,...,90000,2139,0.023767,0,0.000000,18,0.060000,0,0.000000,0
22,sliced_wasserstein,7,8,28,32,300,300,300,300,206,...,90000,2105,0.023389,0,0.000000,16,0.053333,0,0.000000,0
25,sliced_wasserstein,8,9,32,36,300,300,300,300,218,...,90000,2072,0.023022,0,0.000000,17,0.056667,1,0.003333,0
28,sliced_wasserstein,9,10,36,40,300,300,300,300,252,...,90000,2073,0.023033,0,0.000000,9,0.030000,2,0.006667,0
31,sliced_wasserstein,10,11,40,44,300,300,300,300,236,...,90000,2093,0.023256,0,0.000000,11,0.036667,0,0.000000,0
34,sliced_wasserstein,11,12,44,48,300,300,300,300,234,...,90000,2086,0.023178,1,0.003333,12,0.040000,2,0.006667,1
2,sliced_wasserstein_shape,0,1,00,04,300,300,300,300,209,...,90000,2441,0.027122,0,0.000000,13,0.043333,0,0.000000,0
5,sliced_wasserstein_shape,1,2,04,08,300,300,300,300,208,...,90000,2395,0.026611,0,0.000000,16,0.053333,1,0.003333,0
8,sliced_wasserstein_shape,2,3,08,12,300,300,300,300,198,...,90000,2325,0.025833,0,0.000000,10,0.033333,1,0.003333,0
11,sliced_wasserstein_shape,3,4,12,16,300,300,300,300,207,...,90000,2271,0.025233,0,0.000000,16,0.053333,1,0.003333,0
14,sliced_wasserstein_shape,4,5,16,20,300,300,300,300,217,...,90000,2231,0.024789,0,0.000000,8,0.026667,0,0.000000,0
17,sliced_wasserstein_shape,5,6,20,24,300,300,300,300,224,...,90000,2187,0.024300,0,0.000000,11,0.036667,1,0.003333,0
20,sliced_wasserstein_shape,6,7,24,28,300,300,300,300,187,...,90000,2139,0.023767,0,0.000000,18,0.060000,0,0.000000,0
23,sliced_wasserstein_shape,7,8,28,32,300,300,300,300,197,...,90000,2105,0.023389,0,0.000000,16,0.053333,0,0.000000,0
26,sliced_wasserstein_shape,8,9,32,36,300,300,300,300,213,...,90000,2072,0.023022,0,0.000000,17,0.056667,1,0.003333,0
29,sliced_wasserstein_shape,9,10,36,40,300,300,300,300,241,...,90000,2073,0.023033,0,0.000000,9,0.030000,2,0.006667,0
32,sliced_wasserstein_shape,10,11,40,44,300,300,300,300,236,...,90000,2093,0.023256,0,0.000000,11,0.036667,0,0.000000,0
35,sliced_wasserstein_shape,11,12,44,48,300,300,300,300,216,...,90000,2086,0.023178,1,0.003333,12,0.040000,2,0.006667,1

In [48]:
bad_links = result.assignments[result.assignments["is_true_link"] == False]
display(
    bad_links.sort_values(
        ["method", "ref_frame_index", "cost"],
        kind="mergesort",
    ).head(100)
)

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_label,assigned_cand_label,cost,is_true_link,inside_search_radius,radius_relaxed_for_ref,centroid_delta_y,centroid_delta_x,centroid_delta_z,centroid_distance_xy
187,feature_mean,0,1,00,04,188,161,0.010708,False,True,False,-41.871857,-0.572876,1.532661,41.875775
84,feature_mean,0,1,00,04,85,23,0.010820,False,True,False,-34.666656,22.716675,2.900002,41.446645
162,feature_mean,0,1,00,04,163,268,0.010824,False,True,False,17.465736,16.732880,-2.690910,24.187625
242,feature_mean,0,1,00,04,243,193,0.011748,False,True,False,39.481796,-2.952377,5.240898,39.592029
153,feature_mean,0,1,00,04,154,120,0.012258,False,True,False,40.765625,-8.859375,0.125000,41.717199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,feature_mean,0,1,00,04,21,121,0.077238,False,True,False,40.442322,10.442322,-5.557693,41.768690
131,feature_mean,0,1,00,04,132,15,0.080964,False,True,False,49.625000,11.875000,-13.791667,51.026035
140,feature_mean,0,1,00,04,141,71,0.105595,False,True,False,-6.770832,28.187500,-15.729167,28.989297
104,feature_mean,0,1,00,04,105,85,0.130002,False,True,False,-46.661530,4.769226,21.171429,46.904625
1135,feature_mean,1,2,04,08,236,277,0.007103,False,True,False,-26.430847,-9.415222,-3.994072,28.057728

In [49]:
for method, tracks_df in result.tracks.items():
    print(method)
    display(tracks_df.head(40))

feature_mean

,track_id,start,t,x,y,z,A,track_length
0,1,1,1,309.000000,223.000000,12.000000,176.152542,13
1,1,1,2,316.666656,224.079361,12.460318,179.301590,13
2,1,1,3,360.847443,206.966095,10.932203,165.050842,13
3,1,1,4,363.460327,200.174606,8.079365,164.555557,13
4,1,1,5,360.687500,206.578125,9.703125,162.390625,13
5,1,1,6,366.033325,201.966660,9.283334,165.716660,13
6,1,1,7,358.609375,199.078125,14.562500,164.062500,13
7,1,1,8,366.813568,197.271179,16.779661,163.050842,13
8,1,1,9,367.034485,193.810349,17.068966,164.793106,13
9,1,1,10,380.477600,188.014923,12.477612,162.865677,13
10,1,1,11,378.721313,178.360657,12.131147,165.049179,13
11,1,1,12,381.274200,169.451614,9.306452,164.548386,13
12,1,1,13,383.879303,164.034485,8.672414,166.310349,13
13,2,1,1,338.000000,422.000000,40.000000,164.610168,13
14,2,1,2,344.640625,421.781250,42.437500,164.484375,13
15,2,1,3,341.393951,418.666656,38.242424,163.681824,13
16,2,1,4,335.646149,418.569244,39.353848,162.861542,13
17,2,1,5,340.338470,406.907684,38.523075,163.369232,13
18,2,1,6,333.432831,381.298492,34.149254,167.328354,13
19,2,1,7,334.478882,393.661957,38.859154,167.746475,13
20,2,1,8,338.092316,393.969238,44.138462,167.738464,13
21,2,1,9,342.500000,398.500000,42.222221,166.500000,13
22,2,1,10,336.358215,390.029846,42.089554,167.089554,13
23,2,1,11,338.522400,386.074615,40.208954,167.656723,13
24,2,1,12,340.485718,385.171417,34.500000,167.371429,13
25,2,1,13,330.761200,382.119415,37.597015,168.119400,13
26,3,1,1,38.000000,259.000000,49.000000,166.457626,13
27,3,1,2,15.624391,275.352844,47.804878,151.276428,13
28,3,1,3,11.906422,263.488068,56.256882,150.959641,13
29,3,1,4,9.563869,224.062042,45.618614,152.755478,13
30,3,1,5,25.208109,188.716217,42.532433,152.135132,13
31,3,1,6,34.591835,187.969391,40.566326,152.433670,13
32,3,1,7,42.237335,175.621338,45.706665,152.157333,13
33,3,1,8,51.167786,175.617447,46.926174,151.604034,13
34,3,1,9,56.688679,178.443390,44.213837,151.204407,13
35,3,1,10,57.313847,176.846161,43.972309,152.403076,13
36,3,1,11,60.706768,169.839600,49.398495,152.122803,13
37,3,1,12,58.688145,174.610825,45.587627,152.358246,13
38,3,1,13,55.214855,170.883286,46.326260,152.363388,13
39,4,1,1,18.000000,415.000000,29.000000,163.491531,13

sliced_wasserstein

,track_id,start,t,x,y,z,A,track_length
0,1,1,1,309.000000,223.000000,12.000000,176.152542,13
1,1,1,2,316.666656,224.079361,12.460318,179.301590,13
2,1,1,3,360.847443,206.966095,10.932203,165.050842,13
3,1,1,4,363.460327,200.174606,8.079365,164.555557,13
4,1,1,5,360.687500,206.578125,9.703125,162.390625,13
5,1,1,6,366.033325,201.966660,9.283334,165.716660,13
6,1,1,7,358.609375,199.078125,14.562500,164.062500,13
7,1,1,8,366.813568,197.271179,16.779661,163.050842,13
8,1,1,9,367.034485,193.810349,17.068966,164.793106,13
9,1,1,10,380.477600,188.014923,12.477612,162.865677,13
10,1,1,11,378.721313,178.360657,12.131147,165.049179,13
11,1,1,12,381.274200,169.451614,9.306452,164.548386,13
12,1,1,13,383.879303,164.034485,8.672414,166.310349,13
13,2,1,1,338.000000,422.000000,40.000000,164.610168,13
14,2,1,2,344.640625,421.781250,42.437500,164.484375,13
15,2,1,3,341.393951,418.666656,38.242424,163.681824,13
16,2,1,4,335.646149,418.569244,39.353848,162.861542,13
17,2,1,5,340.338470,406.907684,38.523075,163.369232,13
18,2,1,6,333.432831,381.298492,34.149254,167.328354,13
19,2,1,7,334.478882,393.661957,38.859154,167.746475,13
20,2,1,8,338.092316,393.969238,44.138462,167.738464,13
21,2,1,9,342.500000,398.500000,42.222221,166.500000,13
22,2,1,10,336.358215,390.029846,42.089554,167.089554,13
23,2,1,11,338.522400,386.074615,40.208954,167.656723,13
24,2,1,12,340.485718,385.171417,34.500000,167.371429,13
25,2,1,13,330.761200,382.119415,37.597015,168.119400,13
26,3,1,1,38.000000,259.000000,49.000000,166.457626,13
27,3,1,2,15.624391,275.352844,47.804878,151.276428,13
28,3,1,3,11.906422,263.488068,56.256882,150.959641,13
29,3,1,4,9.563869,224.062042,45.618614,152.755478,13
30,3,1,5,9.656250,252.577209,63.948528,148.818008,13
31,3,1,6,11.990706,255.895905,64.061340,148.555756,13
32,3,1,7,28.881226,245.459763,62.898468,147.344833,13
33,3,1,8,11.435484,286.375000,58.592743,155.635086,13
34,3,1,9,37.006382,238.982971,37.761703,157.951065,13
35,3,1,10,53.960213,205.298401,24.246685,154.237396,13
36,3,1,11,40.675747,208.559021,26.736706,154.507141,13
37,3,1,12,67.238098,192.412704,11.126985,163.857147,13
38,3,1,13,90.816330,228.816330,1.244898,164.877548,13
39,4,1,1,18.000000,415.000000,29.000000,163.491531,13

sliced_wasserstein_shape

,track_id,start,t,x,y,z,A,track_length
0,1,1,1,309.000000,223.000000,12.000000,176.152542,13
1,1,1,2,316.666656,224.079361,12.460318,179.301590,13
2,1,1,3,309.758057,214.370972,9.225806,174.725800,13
3,1,1,4,286.432831,225.343277,16.179104,173.582092,13
4,1,1,5,252.273285,187.763977,38.329193,153.338516,13
5,1,1,6,218.003113,189.408096,49.137074,155.112152,13
6,1,1,7,214.258957,220.432510,58.691460,154.977966,13
7,1,1,8,226.601974,236.447372,50.611843,151.875000,13
8,1,1,9,233.902512,235.823898,51.006290,152.172958,13
9,1,1,10,227.348831,235.561050,51.543606,151.563950,13
10,1,1,11,220.574707,232.215515,53.543102,152.235626,13
11,1,1,12,219.605423,233.078308,54.614456,150.512054,13
12,1,1,13,218.086380,239.710968,58.202660,151.418610,13
13,2,1,1,338.000000,422.000000,40.000000,164.610168,13
14,2,1,2,370.865662,419.134338,43.761192,168.164185,13
15,2,1,3,330.451599,388.451599,35.500000,166.919357,13
16,2,1,4,304.111115,422.634918,57.333332,160.444443,13
17,2,1,5,296.836060,441.295074,51.295082,162.639343,13
18,2,1,6,291.338226,431.470581,49.794117,161.455887,13
19,2,1,7,293.218750,438.500000,48.937500,162.546875,13
20,2,1,8,325.500000,437.303040,47.696968,166.696976,13
21,2,1,9,306.212128,447.393951,45.500000,160.090912,13
22,2,1,10,306.451599,453.274200,47.693550,161.951614,13
23,2,1,11,312.636353,456.969696,48.954544,160.439392,13
24,2,1,12,294.852936,497.235291,63.573528,171.132355,13
25,2,1,13,336.096771,489.306458,63.548386,164.032257,13
26,3,1,1,38.000000,259.000000,49.000000,166.457626,13
27,3,1,2,15.624391,275.352844,47.804878,151.276428,13
28,3,1,3,11.906422,263.488068,56.256882,150.959641,13
29,3,1,4,9.563869,224.062042,45.618614,152.755478,13
30,3,1,5,25.208109,188.716217,42.532433,152.135132,13
31,3,1,6,34.591835,187.969391,40.566326,152.433670,13
32,3,1,7,42.237335,175.621338,45.706665,152.157333,13
33,3,1,8,51.167786,175.617447,46.926174,151.604034,13
34,3,1,9,56.688679,178.443390,44.213837,151.204407,13
35,3,1,10,57.313847,176.846161,43.972309,152.403076,13
36,3,1,11,60.706768,169.839600,49.398495,152.122803,13
37,3,1,12,58.688145,174.610825,45.587627,152.358246,13
38,3,1,13,55.214855,170.883286,46.326260,152.363388,13
39,4,1,1,18.000000,415.000000,29.000000,163.491531,13

In [50]:
failures = result.per_object[result.per_object["is_correct"] == False]
display(
    failures.sort_values(
        ["method", "margin", "true_rank"],
        ascending=[True, True, False],
        kind="mergesort",
    ).head(100)
)

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_label,true_cand_label,assigned_cand_label,is_correct,true_rank,true_cost,best_false_cost,margin,true_inside_search_radius,assigned_inside_search_radius,radius_relaxed_for_ref,true_centroid_delta_y,true_centroid_delta_x,true_centroid_delta_z,true_centroid_distance_xy
9231,feature_mean,10,11,40,44,232,232,284,False,11,1.000000e+06,0.013849,-1.000000e+06,False,True,False,-12.250512,54.983948,-0.168137,56.332136
9958,feature_mean,11,12,44,48,59,59,146,False,5,1.000000e+06,0.014588,-1.000000e+06,False,True,False,-10.354767,-57.777863,0.033360,58.698404
8255,feature_mean,9,10,36,40,156,156,238,False,8,1.000000e+06,0.017627,-1.000000e+06,False,True,False,-11.820248,78.183075,14.052374,79.071559
8268,feature_mean,9,10,36,40,169,169,300,False,7,1.000000e+06,0.017909,-1.000000e+06,False,True,False,64.385895,-2.595184,0.083242,64.438175
9107,feature_mean,10,11,40,44,108,108,168,False,9,1.000000e+06,0.019561,-1.000000e+06,False,True,False,71.058189,21.228394,0.055146,74.161385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7250,feature_mean,8,9,32,36,51,51,247,False,5,1.000000e+06,0.032443,-1.000000e+06,False,True,False,68.151520,-72.545441,3.303030,99.536278
1993,feature_mean,2,3,08,12,194,194,182,False,5,1.000000e+06,0.032658,-1.000000e+06,False,True,False,-3.960724,-58.818462,-1.983858,58.951665
2855,feature_mean,3,4,12,16,156,156,159,False,9,1.000000e+06,0.032739,-1.000000e+06,False,True,False,-62.148346,-0.410023,-26.477901,62.149698
7312,feature_mean,8,9,32,36,113,113,123,False,5,1.000000e+06,0.033447,-1.000000e+06,False,True,False,15.611366,-64.019402,-4.522072,65.895360
2095,feature_mean,2,3,08,12,296,296,173,False,11,1.000000e+06,0.034674,-1.000000e+06,False,True,False,16.271149,-52.901028,0.170021,55.346807

In [51]:
display(result.timings)

,stage,seconds,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,method,cost_seconds,assignment_and_scoring_seconds
0,metadata,1.096276,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,signatures,49.773370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pair_costs_and_assignment,0.793387,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,total,51.679513,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0.0,1.0,00,04,feature_mean,0.036566,0.006421
5,NaN,NaN,0.0,1.0,00,04,sliced_wasserstein,0.036566,0.005653
6,NaN,NaN,0.0,1.0,00,04,sliced_wasserstein_shape,0.036566,0.005551
7,NaN,NaN,1.0,2.0,04,08,feature_mean,0.033439,0.006251
8,NaN,NaN,1.0,2.0,04,08,sliced_wasserstein,0.033439,0.006186
9,NaN,NaN,1.0,2.0,04,08,sliced_wasserstein_shape,0.033439,0.005776
10,NaN,NaN,2.0,3.0,08,12,feature_mean,0.033417,0.006578
11,NaN,NaN,2.0,3.0,08,12,sliced_wasserstein,0.033417,0.005542
12,NaN,NaN,2.0,3.0,08,12,sliced_wasserstein_shape,0.033417,0.005971
13,NaN,NaN,3.0,4.0,12,16,feature_mean,0.033262,0.005409
14,NaN,NaN,3.0,4.0,12,16,sliced_wasserstein,0.033262,0.005368
15,NaN,NaN,3.0,4.0,12,16,sliced_wasserstein_shape,0.033262,0.005503
16,NaN,NaN,4.0,5.0,16,20,feature_mean,0.033558,0.005541
17,NaN,NaN,4.0,5.0,16,20,sliced_wasserstein,0.033558,0.005386
18,NaN,NaN,4.0,5.0,16,20,sliced_wasserstein_shape,0.033558,0.005365
19,NaN,NaN,5.0,6.0,20,24,feature_mean,0.033109,0.005449
20,NaN,NaN,5.0,6.0,20,24,sliced_wasserstein,0.033109,0.005089
21,NaN,NaN,5.0,6.0,20,24,sliced_wasserstein_shape,0.033109,0.004947
22,NaN,NaN,6.0,7.0,24,28,feature_mean,0.034746,0.006038
23,NaN,NaN,6.0,7.0,24,28,sliced_wasserstein,0.034746,0.005847
24,NaN,NaN,6.0,7.0,24,28,sliced_wasserstein_shape,0.034746,0.005394
25,NaN,NaN,7.0,8.0,28,32,feature_mean,0.034558,0.005637
26,NaN,NaN,7.0,8.0,28,32,sliced_wasserstein,0.034558,0.005321
27,NaN,NaN,7.0,8.0,28,32,sliced_wasserstein_shape,0.034558,0.005458
28,NaN,NaN,8.0,9.0,32,36,feature_mean,0.033977,0.005682
29,NaN,NaN,8.0,9.0,32,36,sliced_wasserstein,0.033977,0.005800
30,NaN,NaN,8.0,9.0,32,36,sliced_wasserstein_shape,0.033977,0.005778
31,NaN,NaN,9.0,10.0,36,40,feature_mean,0.033091,0.005444
32,NaN,NaN,9.0,10.0,36,40,sliced_wasserstein,0.033091,0.005244
33,NaN,NaN,9.0,10.0,36,40,sliced_wasserstein_shape,0.033091,0.005381
34,NaN,NaN,10.0,11.0,40,44,feature_mean,0.033054,0.005294
35,NaN,NaN,10.0,11.0,40,44,sliced_wasserstein,0.033054,0.005073
36,NaN,NaN,10.0,11.0,40,44,sliced_wasserstein_shape,0.033054,0.005058
37,NaN,NaN,11.0,12.0,44,48,feature_mean,0.032080,0.005593
38,NaN,NaN,11.0,12.0,44,48,sliced_wasserstein,0.032080,0.005443
39,NaN,NaN,11.0,12.0,44,48,sliced_wasserstein_shape,0.032080,0.005621

In [52]:
saved_paths = save_result(result, OUTPUT_PATH)
saved_paths

{'summary_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/summary.csv',
 'aggregate_summary_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/aggregate_summary.csv',
 'per_object_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/per_object.csv',
 'assignments_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/assignments.csv',
 'link_metrics_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/link_metrics.csv',
 'track_points_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/track_points_debug.csv',
 'timings_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/timings.csv',
 'config_json': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/config.json',
 'tracks_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks.csv',
 'tracks_default_method': 'feature_mean',
 'tracks_feature_mean_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks_feature_mean.csv',
 'tracks_sliced_wasserstein_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks_sliced_wasserstein.csv',
 'tracks_sliced_wasserstein_shape_csv': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks_sliced_wasserstein_shape.csv',
 'tracks_by_method': {'feature_mean': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks_by_method/feature_mean/tracks.csv',
  'sliced_wasserstein': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks_by_method/sliced_wasserstein/tracks.csv',
  'sliced_wasserstein_shape': '/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/tests_rope/tracks_by_method/sliced_wasserstein_shape/tracks.csv'}}