# Centroid + Feature Mean Tracking

Barebones adjacent-frame tracking with dense cost matrices and Hungarian assignment. Methods: centroid-only, feature-mean-only, and centroid plus a small clipped feature-mean correction. No shape terms, no search radius, no raw-intensity dependency.

In [14]:
from pathlib import Path
import importlib.util
import json
import sys

import pandas as pd
import torch

repo_root = Path.cwd()
while repo_root != repo_root.parent and not (repo_root / "scripts" / "evaluation" / "feature_mean_tracking.py").exists():
    repo_root = repo_root.parent

module_path = repo_root / "scripts" / "evaluation" / "feature_mean_tracking.py"
if str(module_path.parent) not in sys.path:
    sys.path.insert(0, str(module_path.parent))
spec = importlib.util.spec_from_file_location("feature_mean_tracking", module_path)
feature_mean_tracking = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = feature_mean_tracking
spec.loader.exec_module(feature_mean_tracking)

FeatureMeanConfig = feature_mean_tracking.FeatureMeanConfig
run_feature_mean_tracking = feature_mean_tracking.run_feature_mean_tracking
save_result = feature_mean_tracking.save_result

print(f"repo_root: {repo_root}")
print(f"cuda: {torch.cuda.is_available()} devices={torch.cuda.device_count()}")

repo_root: /nfs/scratch2/inacio/code/llsm/spatialdino/spatialdino
cuda: True devices=1

In [30]:
# Edit these paths before running.
INPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/rope/")
SEGMENTATION_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/gt/")
OUTPUT_PATH = Path("/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/")

MAX_FRAMES = None
COMPUTE_GT_METRICS = True

METHODS = ("centroid", "feature_mean", "centroid_feature")
TRACKS_METHOD = "centroid_feature"
CENTROID_FEATURE_WEIGHT = 0.01
FEATURE_NORM_CLIP = 3.0
Z_WEIGHT = 2.5

DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

In [31]:
config = FeatureMeanConfig(
    n_features=384,
    samples_per_object=128,
    seed=12345,
    device=DEVICE,
    methods=METHODS,
    tracks_method=TRACKS_METHOD,
    centroid_feature_weight=CENTROID_FEATURE_WEIGHT,
    feature_norm_clip=FEATURE_NORM_CLIP,
    z_weight=Z_WEIGHT,
    max_frames=MAX_FRAMES,
    compute_gt_metrics=COMPUTE_GT_METRICS,
    progress=True,
)

config

FeatureMeanConfig(n_features=384, samples_per_object=128, seed=12345, device='cuda:0', methods=('centroid', 'feature_mean', 'centroid_feature'), tracks_method='centroid_feature', centroid_feature_weight=0.01, feature_norm_clip=3.0, z_weight=2.5, max_frames=None, compute_gt_metrics=True, progress=True, object_batch_size=512, feature_channel_block=64, sample_batch_size=131072)

In [32]:
result = run_feature_mean_tracking(
    INPUT_PATH,
    SEGMENTATION_PATH,
    config=config,
)

saved_paths = save_result(result, OUTPUT_PATH)
print(json.dumps(saved_paths, indent=2))

[feature-mean-tracking] found 13 frame(s); using 384/390 feature channel(s), 128 sample(s)/object, methods=('centroid', 'feature_mean', 'centroid_feature'), device=cuda:0

feature means:   0%|                                                                                          …

[feature-mean-tracking] feature means completed in 14.32s

adjacent pairs:   0%|                                                                                         …

[feature-mean-tracking] matching and tracks completed in 0.24s; total 14.57s
{
  "tracks_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks.csv",
  "assignments_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/assignments.csv",
  "timings_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/timings.csv",
  "config_json": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/config.json",
  "tracks_centroid_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks_centroid.csv",
  "tracks_centroid_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks_by_method/centroid/tracks.csv",
  "tracks_feature_mean_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks_feature_mean.csv",
  "tracks_feature_mean_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks_by_method/feature_mean/tracks.csv",
  "tracks_centroid_feature_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks_centroid_feature.csv",
  "tracks_centroid_feature_nested_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/tracks_by_method/centroid_feature/tracks.csv",
  "tracks_default_method": "centroid_feature",
  "metrics_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/metrics.csv",
  "pair_metrics_csv": "/nfs/scratch2/inacio/data/llsm/spatialdino/model_final/results/simulated_new/fast_gap/n_300/gap_3/feature_mean_tracking/pair_metrics.csv"
}

In [29]:
display(result.metrics if result.metrics is not None else pd.DataFrame())
display(result.pair_metrics.head(20) if result.pair_metrics is not None else pd.DataFrame())

,method,frame_pairs,trackable_count,link_pred_count,link_tp,link_fp,link_fn,precision,recall,f1,median_centroid_scale,median_feature_scale,centroid_feature_weight,feature_norm_clip
0,centroid,12,3600,3600,3162,438,438,0.878333,0.878333,0.878333,266.472183,NaN,NaN,NaN
1,feature_mean,12,3600,3600,2339,1261,1261,0.649722,0.649722,0.649722,NaN,0.077283,NaN,NaN
2,centroid_feature,12,3600,3600,3222,378,378,0.895000,0.895000,0.895000,266.472183,0.077283,0.5,3.0

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_count,cand_count,trackable_count,link_pred_count,link_tp,link_fp,link_fn,precision,recall,f1,centroid_scale,feature_scale,centroid_feature_weight,feature_norm_clip
0,centroid,0,1,00,04,300,300,300,300,247,53,53,0.823333,0.823333,0.823333,256.756958,NaN,NaN,NaN
1,feature_mean,0,1,00,04,300,300,300,300,175,125,125,0.583333,0.583333,0.583333,NaN,0.080088,NaN,NaN
2,centroid_feature,0,1,00,04,300,300,300,300,251,49,49,0.836667,0.836667,0.836667,256.756958,0.080088,0.5,3.0
3,centroid,1,2,04,08,300,300,300,300,264,36,36,0.880000,0.880000,0.880000,259.025940,NaN,NaN,NaN
4,feature_mean,1,2,04,08,300,300,300,300,180,120,120,0.600000,0.600000,0.600000,NaN,0.078708,NaN,NaN
5,centroid_feature,1,2,04,08,300,300,300,300,259,41,41,0.863333,0.863333,0.863333,259.025940,0.078708,0.5,3.0
6,centroid,2,3,08,12,300,300,300,300,267,33,33,0.890000,0.890000,0.890000,261.065765,NaN,NaN,NaN
7,feature_mean,2,3,08,12,300,300,300,300,181,119,119,0.603333,0.603333,0.603333,NaN,0.076411,NaN,NaN
8,centroid_feature,2,3,08,12,300,300,300,300,267,33,33,0.890000,0.890000,0.890000,261.065765,0.076411,0.5,3.0
9,centroid,3,4,12,16,300,300,300,300,260,40,40,0.866667,0.866667,0.866667,262.783264,NaN,NaN,NaN
10,feature_mean,3,4,12,16,300,300,300,300,203,97,97,0.676667,0.676667,0.676667,NaN,0.076544,NaN,NaN
11,centroid_feature,3,4,12,16,300,300,300,300,264,36,36,0.880000,0.880000,0.880000,262.783264,0.076544,0.5,3.0
12,centroid,4,5,16,20,300,300,300,300,272,28,28,0.906667,0.906667,0.906667,263.885437,NaN,NaN,NaN
13,feature_mean,4,5,16,20,300,300,300,300,211,89,89,0.703333,0.703333,0.703333,NaN,0.077260,NaN,NaN
14,centroid_feature,4,5,16,20,300,300,300,300,274,26,26,0.913333,0.913333,0.913333,263.885437,0.077260,0.5,3.0
15,centroid,5,6,20,24,300,300,300,300,266,34,34,0.886667,0.886667,0.886667,265.610229,NaN,NaN,NaN
16,feature_mean,5,6,20,24,300,300,300,300,204,96,96,0.680000,0.680000,0.680000,NaN,0.077306,NaN,NaN
17,centroid_feature,5,6,20,24,300,300,300,300,271,29,29,0.903333,0.903333,0.903333,265.610229,0.077306,0.5,3.0
18,centroid,6,7,24,28,300,300,300,300,262,38,38,0.873333,0.873333,0.873333,267.334137,NaN,NaN,NaN
19,feature_mean,6,7,24,28,300,300,300,300,172,128,128,0.573333,0.573333,0.573333,NaN,0.076904,NaN,NaN

In [19]:
display(result.assignments.head(50))

,method,ref_frame_index,cand_frame_index,ref_timepoint,cand_timepoint,ref_label,assigned_cand_label,cost,is_true_link
0,centroid,0,1,00,04,1,1,0.030817,True
1,centroid,0,1,00,04,2,2,0.032573,True
2,centroid,0,1,00,04,3,3,0.104902,True
3,centroid,0,1,00,04,4,4,0.058005,True
4,centroid,0,1,00,04,5,252,0.110008,False
5,centroid,0,1,00,04,6,6,0.063326,True
6,centroid,0,1,00,04,7,7,0.028475,True
7,centroid,0,1,00,04,8,8,0.115334,True
8,centroid,0,1,00,04,9,9,0.021009,True
9,centroid,0,1,00,04,10,102,0.027259,False
10,centroid,0,1,00,04,11,11,0.030176,True
11,centroid,0,1,00,04,12,12,0.028210,True
12,centroid,0,1,00,04,13,87,0.080086,False
13,centroid,0,1,00,04,14,14,0.028874,True
14,centroid,0,1,00,04,15,132,0.153246,False
15,centroid,0,1,00,04,16,16,0.040532,True
16,centroid,0,1,00,04,17,210,0.030363,False
17,centroid,0,1,00,04,18,18,0.104622,True
18,centroid,0,1,00,04,19,19,0.057515,True
19,centroid,0,1,00,04,20,20,0.031427,True
20,centroid,0,1,00,04,21,21,0.043669,True
21,centroid,0,1,00,04,22,22,0.058702,True
22,centroid,0,1,00,04,23,23,0.039341,True
23,centroid,0,1,00,04,24,24,0.048500,True
24,centroid,0,1,00,04,25,25,0.035290,True
25,centroid,0,1,00,04,26,26,0.010406,True
26,centroid,0,1,00,04,27,27,0.035706,True
27,centroid,0,1,00,04,28,28,0.045064,True
28,centroid,0,1,00,04,29,29,0.080024,True
29,centroid,0,1,00,04,30,30,0.029851,True
30,centroid,0,1,00,04,31,31,0.041642,True
31,centroid,0,1,00,04,32,32,0.027139,True
32,centroid,0,1,00,04,33,33,0.229345,True
33,centroid,0,1,00,04,34,34,0.013328,True
34,centroid,0,1,00,04,35,35,0.041965,True
35,centroid,0,1,00,04,36,36,0.058445,True
36,centroid,0,1,00,04,37,269,0.079955,False
37,centroid,0,1,00,04,38,38,0.056321,True
38,centroid,0,1,00,04,39,39,0.022713,True
39,centroid,0,1,00,04,40,40,0.055000,True
40,centroid,0,1,00,04,41,41,0.021980,True
41,centroid,0,1,00,04,42,42,0.048395,True
42,centroid,0,1,00,04,43,43,0.042474,True
43,centroid,0,1,00,04,44,44,0.063016,True
44,centroid,0,1,00,04,45,45,0.045263,True
45,centroid,0,1,00,04,46,46,0.025225,True
46,centroid,0,1,00,04,47,47,0.042889,True
47,centroid,0,1,00,04,48,156,0.181122,False
48,centroid,0,1,00,04,49,49,0.052207,True
49,centroid,0,1,00,04,50,50,0.011433,True

In [20]:
display(result.tracks.head(50))

    track_id  start   t           x           y          z    A  track_length
0          1      1   1  309.000000  223.000000  12.000000  1.0            13
1          1      1   2  316.666656  224.079361  12.460318  1.0            13
2          1      1   3  309.758057  214.370972   9.225806  1.0            13
3          1      1   4  286.432831  225.343277  16.179104  1.0            13
4          1      1   5  289.343750  247.937500  28.500000  1.0            13
5          1      1   6  287.671875  252.109375  36.562500  1.0            13
6          1      1   7  261.671875  236.453125  47.359375  1.0            13
7          1      1   8  246.079361  244.174606  51.269840  1.0            13
8          1      1   9  228.344315  289.781433  63.452095  1.0            13
9          1      1  10  228.590912  311.818176  60.878788  1.0            13
10         1      1  11  223.393936  318.333344  57.242424  1.0            13
11         1      1  12  213.731339  317.567169  57.537312  1.0            13
12         1      1  13  212.298508  309.671631  53.298508  1.0            13
13         2      1   1  338.000000  422.000000  40.000000  1.0            13
14         2      1   2  344.640625  421.781250  42.437500  1.0            13
15         2      1   3  341.393951  418.666656  38.242424  1.0            13
16         2      1   4  335.646149  418.569244  39.353848  1.0            13
17         2      1   5  340.338470  406.907684  38.523075  1.0            13
18         2      1   6  347.218750  401.453125  32.000000  1.0            13
19         2      1   7  338.507690  398.215393  34.246155  1.0            13
20         2      1   8  335.420288  401.072449  41.028984  1.0            13
21         2      1   9  342.500000  398.500000  42.222221  1.0            13
22         2      1  10  336.358215  390.029846  42.089554  1.0            13
23         2      1  11  338.522400  386.074615  40.208954  1.0            13
24         2      1  12  340.485718  385.171417  34.500000  1.0            13
25         2      1  13  330.761200  382.119415  37.597015  1.0            13
26         3      1   1   38.000000  259.000000  49.000000  1.0            13
27         3      1   2   15.624391  275.352844  47.804878  1.0            13
28         3      1   3   11.906422  263.488068  56.256882  1.0            13
29         3      1   4    9.227627  275.900787  64.782104  1.0            13
30         3      1   5    1.725490  282.627441  67.705879  1.0            13
31         3      1   6    1.629630  273.629639  67.462959  1.0            13
32         3      1   7    2.617647  208.455887  65.279411  1.0            13
33         3      1   8    7.293334  119.535240  58.055237  1.0            13
34         3      1   9    8.641233   72.944809  64.754868  1.0            13
35         3      1  10   11.140379   45.668770  66.283913  1.0            13
36         3      1  11   10.365177   12.756549  65.607086  1.0            13
37         3      1  12    8.012423   15.357142  63.787266  1.0            13
38         3      1  13   10.267606    9.771518  53.848202  1.0            13
39         4      1   1   18.000000  415.000000  29.000000  1.0            13
40         4      1   2   22.400000  415.057129  22.000000  1.0            13
41         4      1   3   16.500000  409.500000  20.500000  1.0            13
42         4      1   4   15.132353  446.470581  13.720589  1.0            13
43         4      1   5   23.353846  457.569244   6.646154  1.0            13
44         4      1   6   22.586666  455.506653   3.960000  1.0            13
45         4      1   7   27.500000  450.500000   1.083333  1.0            13
46         4      1   8   20.413794  442.655182   1.637931  1.0            13
47         4      1   9   18.372549  457.725494   1.294118  1.0            13
48         4      1  10   15.656250  476.875000   3.281250  1.0            13
49         4      1  11   13.810811  495.864868   1.135135  1.0            13